#!/usr/bin/env bash
# Regenerate CLAUDE.md's "## Content Inventory" from what is actually on disk.
#
# The inventory rotted badly once already: an entire stack (engineering, 5 skills) plus three
# global skills were missing, every line count was stale, and the Agents table asserted a `model:`
# for eight agents whose files did not carry one. A hand-maintained inventory in the very file
# that is loaded into context is worse than none — an agent reads it, believes the repo has no
# engineering pack, and rebuilds what already exists.
#
# Run this after adding, removing, or materially growing a skill or agent.
set -euo pipefail

cd "$(dirname "$0")/.."

python3 - <<'PY'
import os, re, glob

def fm(p):
    m = re.search(r"^---\n(.*?)\n---", open(p).read(), re.S)
    return m.group(1) if m else ""

def field(p, key):
    for line in fm(p).split("\n"):
        if line.startswith(key + ":"):
            return line.split(":", 1)[1].strip()
    return ""

def nlines(p):
    return sum(1 for _ in open(p))

def table(rows, hdr):
    n = len(hdr)
    w = [max(len(hdr[i]), max((len(r[i]) for r in rows), default=0)) for i in range(n)]
    ln = lambda c: "| " + " | ".join(c[i].ljust(w[i]) for i in range(n)) + " |"
    return "\n".join([ln(hdr), "| " + " | ".join("-" * w[i] for i in range(n)) + " |"]
                     + [ln(r) for r in rows])

STUB_MAX = 40  # a SKILL.md at or under this is a stub, not content

agents = []
for a in sorted(glob.glob("agents/*/*.md")):
    if os.path.basename(a) == "CLAUDE.md":
        continue
    d = field(a, "description")
    d = d.split(". Triggers on")[0].split(". Use PROACTIVELY")[0].rstrip(".")
    if len(d) > 78:
        d = d[:75].rstrip() + "..."
    agents.append((field(a, "name") or os.path.basename(a)[:-3], a.split("/")[1],
                   field(a, "model") or "MISSING", str(nlines(a)), d))
order = {"universal": 0, "frontend": 1, "flutter": 2, "python": 3, "rust": 4}
agents.sort(key=lambda r: (order.get(r[1], 9), r[0]))

complete, stubs = [], []
for s in sorted(glob.glob("skills/*/*/SKILL.md")):
    n = nlines(s)
    d = re.split(r"[.—]", field(s, "description"))[0].strip()
    if len(d) > 84:
        d = d[:81].rstrip() + "..."
    (stubs if n <= STUB_MAX else complete).append((s.split("/")[2], s.split("/")[1], str(n), d))
complete.sort(key=lambda r: -int(r[2]))
stubs.sort(key=lambda r: (r[1], r[0]))

block = (
    "## Content Inventory\n\n"
    "> Regenerated by `verify-scripts/regenerate-inventory.sh` — do not hand-edit the rows.\n"
    f"> A `SKILL.md` of {STUB_MAX} lines or fewer counts as a stub.\n\n"
    "### Agents\n\n" + table(agents, ("Agent", "Stack", "Model", "Lines", "Description")) + "\n\n"
    "### Skills — Complete\n\n" + table(complete, ("Skill", "Stack", "Lines", "Description")) + "\n\n"
    "### Skills — Stubs (need content)\n\n"
    + table([(r[0], r[1], r[2]) for r in stubs], ("Skill", "Stack", "Lines")) + "\n\n"
)

src = open("CLAUDE.md").read()
start, end = src.index("## Content Inventory"), src.index("## Conventions")
open("CLAUDE.md", "w").write(src[:start] + block + src[end:])

missing = [a[0] + " (" + a[1] + ")" for a in agents if a[2] == "MISSING"]
print("CLAUDE.md inventory regenerated: "
      f"{len(agents)} agents, {len(complete)} skills, {len(stubs)} stubs")
if missing:
    raise SystemExit("ERROR: agents missing a required `model:` field: " + ", ".join(missing))
PY
